database:
  username: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
  driver: org.postgresql.Driver

spring:
  datasource:
    initialization-mode: always

footballDataToken: ENC(go3QTKBTDr/y5hMBUxpgrsYOitF0o2t3LZvpRGkx8a82xdbsG7JGqjRyJ5VwHahA)
